name: Build and push golem-toy image
on:
  push:
    tags:
      - 'v*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        # https://github.community/t/how-to-get-just-the-tag-name/16241/5
        name: Get the tag name
        id: get_tag
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF/refs\/tags\//}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ursueugen/golex-toy:$TAG_NAME
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
