name: Build and push golem-toy image
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v**'
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ursueugen/golex-toy
          tag_with_ref: true
